name: Build PR

on:
  pull_request:
    branches: [ main ]
    paths-ignore: # do not trigger for changes:
      - README.md
      - LICENSE
      - CHANGELOG.md
      - docs/**

jobs:
  Build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
          - "pypy-3.8"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required for GitVersion

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v2
        with:
          versionSpec: '5.x'

      - name: Determine Version
        uses: gittools/actions/gitversion/execute@v2
        with:
          useConfigFile: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip and virtualenv to latest
        run: pip install --upgrade pip virtualenv

      - name: Install Falu
        run: python setup.py install

      - name: 'pytest'
        run: |
          pip install pytest pytest-cov
          pytest --junitxml=junit/test-results.xml --cov=falu --cov-report=xml --cov-report=html

      - name: Publish pytest results
        uses: pmeier/pytest-results-action@v0.7.1
        with:
          path: 'junit/test-results.xml'
          title: 'Test results falu'
          summary: true
